# Placeholder for internal Python library.
# Placeholder for internal Python test library.

package(
    default_visibility = [
        "//merlin_kv:__subpackages__",
    ],
)

licenses(["notice"])  # Apache 2.0

# Tests
py_test(
    name = "merlin_kv_variable_test",
    srcs = ["merlin_kv_test.py"],
    python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//merlin_kv",
    ],
)
